name = "chat"
main = "functions/api/chat.js"
compatibility_date = "2026-07-02"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "chatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["chatRoom"]